openrange:
- name: utg
  range:
    "AA": 0
  regexp: ^(A.{1,}s)|AA|KK|QQ|JJ|TT|99|88|77|66|55|44|33|22|A[K|Q|J|T]o|KQo|K[Q|J|T]s|Q[J|T]s|JTs|T9s|98s|87s|76s$
- name: mp
  range:
    "AA": 0
  regexp: ^(A.{1,}s)|AA|KK|QQ|JJ|TT|99|88|77|66|55|44|33|22|A[K|Q|J|T]o|K[Q|J]o|K[Q|J|T]s|Q[J|T]s|JTs|98s|87s|76s|56s|[K|Q|J|T]9s$
- name: co
  range:
    "AA": 0
  regexp: ^(A.{1,}s)|AA|KK|QQ|JJ|TT|99|88|77|66|55|44|33|22|A[K|Q|J|T|9]o|K[Q|J|T]o|Q[J|T]o|TJo|K[Q|J|T]s|K[5-9]s|Q[J|T|6-9]s|J[T|9]s|T[8-9]s|9[7-8]s|8[6-7]s|76s|56s$
- name: btn
  range:
    "AA": 0
  regexp: ^([A|K|Q|J].{1,}s)|AA|KK|QQ|JJ|TT|99|88|77|66|55|44|33|22|A.{1,}o|K[Q|J|T|6-9]o|Q[J|T|7-9]o|J[T|8-9]o|T[8-9]o|98o|87o|76o|T[5-9]s|9[5-8]s|8[5-7]s|7[4-6]s|6[4-5]s|5[3-4]s|43s$
- name: sb
  range:
    "AA": 0
  regexp: ^([A|K|Q|J|T].{1,}s)|A.{1,}o|AA|KK|QQ|JJ|TT|99|88|77|66|55|44|33|22|K[Q|J|T|5-9]o|Q[J|T|7-9]o|J[T|7-9]o|T[8-9]o|9[7-8]o|87o|76o|65o|T[5-9]s|9[4-8]s|8[4-7]s|7[4-6]s|6[3-5]s|5[2-4]s|4[2-3]s$
